spring.application.name=products
server.port = 8100

order.id.required=Order ID is mandatory and cannot be empty.
customer.id.required=Customer ID is required for every order.
products.required=An order must contain at least one product.
payment.required = An order must contain payment details
shipping.required = An order must contain at least one shipping address


# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:./data/ecomdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Automatically create/update tables based on Entity classes
spring.jpa.hibernate.ddl-auto=update

# Enable H2 Console (accessible at http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL in logs (useful for debugging table creation)
spring.jpa.show-sql=true